[project]
src = "src"
out = "out"
dot_env = ".env"

[networks.contracts.vrf_coordinator]
deployer_script = "deploy_mock.py"

[networks.contracts.vrf_wrapper]
deployer_script = "deploy_mock.py"

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.sepolia]
url = "$Sepolia_RPC"
chain_id = 11155111
save_to_db = false
default_account_name="default"
explorer_uri ="https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.sepolia.contracts.vrf_coordinator]
address = "$VRF_Wrapper"

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
